name: Update README

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      run: python codeforces_stats.py

    - name: Commit and push if changed
      run: |
        git diff
        git config --local user.email "contact@kacperbak.pl"
        git config --local user.name "53jk1"
        git commit -am "Update README" || exit 0
        git push origin HEAD:main --follow-tags --force-with-lease || echo "No changes to commit"
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
