name: Update README

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
        token: ${{ secrets.GH_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      run: python codeforces_stats.py
      
    - name: Get current time
      id: current-time
      run: echo "::set-output name=time::$(date)"

    - name: Commit and push if changed
      run: |
        git diff
        git config --local user.email "contact@kacperbak.pl"
        git config --local user.name "Kacper Bąk"
        git commit -am "Update README at ${{ steps.current-time.outputs.time }}" || exit 0
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
        git push
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
